services:
  - type: web
    name: fraudlens-ai-rohit97116
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
